use_frameworks!

platform :ios, '10.0'

target 'PSTestPods_Example' do
  pod 'PSTestPods', :path => '../'

  target 'PSTestPods_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
